### ISSUE TITLE
[EnumConstraint] don't assume TParam may be nullable

### ISSUE THREAD

**Issue by bessgeor** [Fody/ExtraConstraints#15]
See repro 2 at https://github.com/bessgeor/ExtraConstraintsRepro.
Maybe actual problem is in #14.

**Comment by SimonCropp** [comment]
repro doesnt compile

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0453	The type 'TEnum' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'Nullable<T>'	ExtraConstraintsRepro	C:\Code\ExtraConstraintsRepro\ExtraConstraintsRepro\ConstraintOnNullableEnumDoesntCompileWithoutStructConstraint.cs	17	Active

**Comment by bessgeor** [comment]
That's the thing of the repro. `TEnum` is annotated with `[EnumConstraint]` and all of the enums in C# are structs (non-nullable). So I expect `[EnumConstraint]` to constraint `TEnum` to `struct` behind the scene but it does not thus resulting in compilation error.
